/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.community.protocol.thrift.roomgate;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ChatType implements org.apache.thrift.TEnum {
  PRIVATE_CHAT(0),
  PUBLIC_CHAT(1),
  AUTO_REPLY(2),
  USER_MOOD(4),
  POKE(8),
  SHAKE_WINDOW(16);

  private final int value;

  private ChatType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ChatType findByValue(int value) { 
    switch (value) {
      case 0:
        return PRIVATE_CHAT;
      case 1:
        return PUBLIC_CHAT;
      case 2:
        return AUTO_REPLY;
      case 4:
        return USER_MOOD;
      case 8:
        return POKE;
      case 16:
        return SHAKE_WINDOW;
      default:
        return null;
    }
  }
}
