/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.community.protocol.thrift.roomgate;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MessageType implements org.apache.thrift.TEnum {
  MT_CONNECT_REQ(600),
  MT_CONNECT_RES(601),
  MT_GET_ROOMLIST_REQ(602),
  MT_GET_ROOMLIST_RES(603),
  MT_UPDATE_ROOMLIST_NOTIFY(604),
  UPDATE_USERINFO_REQ(605),
  UPDATE_USERINFO_RES(606),
  MT_CHAT_REQ(607),
  MT_CHAT_RES(608),
  MT_CHAT_NOTIFY(609);

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MessageType findByValue(int value) { 
    switch (value) {
      case 600:
        return MT_CONNECT_REQ;
      case 601:
        return MT_CONNECT_RES;
      case 602:
        return MT_GET_ROOMLIST_REQ;
      case 603:
        return MT_GET_ROOMLIST_RES;
      case 604:
        return MT_UPDATE_ROOMLIST_NOTIFY;
      case 605:
        return UPDATE_USERINFO_REQ;
      case 606:
        return UPDATE_USERINFO_RES;
      case 607:
        return MT_CHAT_REQ;
      case 608:
        return MT_CHAT_RES;
      case 609:
        return MT_CHAT_NOTIFY;
      default:
        return null;
    }
  }
}
