/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.community.protocol.thrift.roomgate;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2019-10-12")
public class RoomgateConnectChecksum implements org.apache.thrift.TBase<RoomgateConnectChecksum, RoomgateConnectChecksum._Fields>, java.io.Serializable, Cloneable, Comparable<RoomgateConnectChecksum> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RoomgateConnectChecksum");

  private static final org.apache.thrift.protocol.TField ROOMGATE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("roomgate_id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CLIENT_RANDOM_FIELD_DESC = new org.apache.thrift.protocol.TField("client_random", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField SERVER_RANDOM_FIELD_DESC = new org.apache.thrift.protocol.TField("server_random", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RoomgateConnectChecksumStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RoomgateConnectChecksumTupleSchemeFactory();

  public java.lang.String roomgate_id; // required
  public long client_random; // required
  public long server_random; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ROOMGATE_ID((short)1, "roomgate_id"),
    CLIENT_RANDOM((short)2, "client_random"),
    SERVER_RANDOM((short)3, "server_random");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ROOMGATE_ID
          return ROOMGATE_ID;
        case 2: // CLIENT_RANDOM
          return CLIENT_RANDOM;
        case 3: // SERVER_RANDOM
          return SERVER_RANDOM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CLIENT_RANDOM_ISSET_ID = 0;
  private static final int __SERVER_RANDOM_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ROOMGATE_ID, new org.apache.thrift.meta_data.FieldMetaData("roomgate_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLIENT_RANDOM, new org.apache.thrift.meta_data.FieldMetaData("client_random", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SERVER_RANDOM, new org.apache.thrift.meta_data.FieldMetaData("server_random", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RoomgateConnectChecksum.class, metaDataMap);
  }

  public RoomgateConnectChecksum() {
  }

  public RoomgateConnectChecksum(
    java.lang.String roomgate_id,
    long client_random,
    long server_random)
  {
    this();
    this.roomgate_id = roomgate_id;
    this.client_random = client_random;
    setClient_randomIsSet(true);
    this.server_random = server_random;
    setServer_randomIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RoomgateConnectChecksum(RoomgateConnectChecksum other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetRoomgate_id()) {
      this.roomgate_id = other.roomgate_id;
    }
    this.client_random = other.client_random;
    this.server_random = other.server_random;
  }

  public RoomgateConnectChecksum deepCopy() {
    return new RoomgateConnectChecksum(this);
  }

  @Override
  public void clear() {
    this.roomgate_id = null;
    setClient_randomIsSet(false);
    this.client_random = 0;
    setServer_randomIsSet(false);
    this.server_random = 0;
  }

  public java.lang.String getRoomgate_id() {
    return this.roomgate_id;
  }

  public RoomgateConnectChecksum setRoomgate_id(java.lang.String roomgate_id) {
    this.roomgate_id = roomgate_id;
    return this;
  }

  public void unsetRoomgate_id() {
    this.roomgate_id = null;
  }

  /** Returns true if field roomgate_id is set (has been assigned a value) and false otherwise */
  public boolean isSetRoomgate_id() {
    return this.roomgate_id != null;
  }

  public void setRoomgate_idIsSet(boolean value) {
    if (!value) {
      this.roomgate_id = null;
    }
  }

  public long getClient_random() {
    return this.client_random;
  }

  public RoomgateConnectChecksum setClient_random(long client_random) {
    this.client_random = client_random;
    setClient_randomIsSet(true);
    return this;
  }

  public void unsetClient_random() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CLIENT_RANDOM_ISSET_ID);
  }

  /** Returns true if field client_random is set (has been assigned a value) and false otherwise */
  public boolean isSetClient_random() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CLIENT_RANDOM_ISSET_ID);
  }

  public void setClient_randomIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CLIENT_RANDOM_ISSET_ID, value);
  }

  public long getServer_random() {
    return this.server_random;
  }

  public RoomgateConnectChecksum setServer_random(long server_random) {
    this.server_random = server_random;
    setServer_randomIsSet(true);
    return this;
  }

  public void unsetServer_random() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SERVER_RANDOM_ISSET_ID);
  }

  /** Returns true if field server_random is set (has been assigned a value) and false otherwise */
  public boolean isSetServer_random() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SERVER_RANDOM_ISSET_ID);
  }

  public void setServer_randomIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SERVER_RANDOM_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ROOMGATE_ID:
      if (value == null) {
        unsetRoomgate_id();
      } else {
        setRoomgate_id((java.lang.String)value);
      }
      break;

    case CLIENT_RANDOM:
      if (value == null) {
        unsetClient_random();
      } else {
        setClient_random((java.lang.Long)value);
      }
      break;

    case SERVER_RANDOM:
      if (value == null) {
        unsetServer_random();
      } else {
        setServer_random((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ROOMGATE_ID:
      return getRoomgate_id();

    case CLIENT_RANDOM:
      return getClient_random();

    case SERVER_RANDOM:
      return getServer_random();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ROOMGATE_ID:
      return isSetRoomgate_id();
    case CLIENT_RANDOM:
      return isSetClient_random();
    case SERVER_RANDOM:
      return isSetServer_random();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RoomgateConnectChecksum)
      return this.equals((RoomgateConnectChecksum)that);
    return false;
  }

  public boolean equals(RoomgateConnectChecksum that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_roomgate_id = true && this.isSetRoomgate_id();
    boolean that_present_roomgate_id = true && that.isSetRoomgate_id();
    if (this_present_roomgate_id || that_present_roomgate_id) {
      if (!(this_present_roomgate_id && that_present_roomgate_id))
        return false;
      if (!this.roomgate_id.equals(that.roomgate_id))
        return false;
    }

    boolean this_present_client_random = true;
    boolean that_present_client_random = true;
    if (this_present_client_random || that_present_client_random) {
      if (!(this_present_client_random && that_present_client_random))
        return false;
      if (this.client_random != that.client_random)
        return false;
    }

    boolean this_present_server_random = true;
    boolean that_present_server_random = true;
    if (this_present_server_random || that_present_server_random) {
      if (!(this_present_server_random && that_present_server_random))
        return false;
      if (this.server_random != that.server_random)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetRoomgate_id()) ? 131071 : 524287);
    if (isSetRoomgate_id())
      hashCode = hashCode * 8191 + roomgate_id.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(client_random);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(server_random);

    return hashCode;
  }

  @Override
  public int compareTo(RoomgateConnectChecksum other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetRoomgate_id()).compareTo(other.isSetRoomgate_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoomgate_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roomgate_id, other.roomgate_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetClient_random()).compareTo(other.isSetClient_random());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClient_random()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.client_random, other.client_random);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetServer_random()).compareTo(other.isSetServer_random());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetServer_random()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.server_random, other.server_random);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RoomgateConnectChecksum(");
    boolean first = true;

    sb.append("roomgate_id:");
    if (this.roomgate_id == null) {
      sb.append("null");
    } else {
      sb.append(this.roomgate_id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("client_random:");
    sb.append(this.client_random);
    first = false;
    if (!first) sb.append(", ");
    sb.append("server_random:");
    sb.append(this.server_random);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RoomgateConnectChecksumStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RoomgateConnectChecksumStandardScheme getScheme() {
      return new RoomgateConnectChecksumStandardScheme();
    }
  }

  private static class RoomgateConnectChecksumStandardScheme extends org.apache.thrift.scheme.StandardScheme<RoomgateConnectChecksum> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RoomgateConnectChecksum struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ROOMGATE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.roomgate_id = iprot.readString();
              struct.setRoomgate_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CLIENT_RANDOM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.client_random = iprot.readI64();
              struct.setClient_randomIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SERVER_RANDOM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.server_random = iprot.readI64();
              struct.setServer_randomIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RoomgateConnectChecksum struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.roomgate_id != null) {
        oprot.writeFieldBegin(ROOMGATE_ID_FIELD_DESC);
        oprot.writeString(struct.roomgate_id);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(CLIENT_RANDOM_FIELD_DESC);
      oprot.writeI64(struct.client_random);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SERVER_RANDOM_FIELD_DESC);
      oprot.writeI64(struct.server_random);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RoomgateConnectChecksumTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RoomgateConnectChecksumTupleScheme getScheme() {
      return new RoomgateConnectChecksumTupleScheme();
    }
  }

  private static class RoomgateConnectChecksumTupleScheme extends org.apache.thrift.scheme.TupleScheme<RoomgateConnectChecksum> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RoomgateConnectChecksum struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetRoomgate_id()) {
        optionals.set(0);
      }
      if (struct.isSetClient_random()) {
        optionals.set(1);
      }
      if (struct.isSetServer_random()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetRoomgate_id()) {
        oprot.writeString(struct.roomgate_id);
      }
      if (struct.isSetClient_random()) {
        oprot.writeI64(struct.client_random);
      }
      if (struct.isSetServer_random()) {
        oprot.writeI64(struct.server_random);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RoomgateConnectChecksum struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.roomgate_id = iprot.readString();
        struct.setRoomgate_idIsSet(true);
      }
      if (incoming.get(1)) {
        struct.client_random = iprot.readI64();
        struct.setClient_randomIsSet(true);
      }
      if (incoming.get(2)) {
        struct.server_random = iprot.readI64();
        struct.setServer_randomIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

